/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CalculatorSalariuNet2018;

import java.awt.Dialog;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.*;
import javax.swing.InputVerifier;
/**
 *
 * @author Admin
 */
public class CalculatorSalariuNet2018 extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorSalariuNet2018
     */
    public CalculatorSalariuNet2018() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Calculeaza = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        CAS25 = new javax.swing.JLabel();
        CAS10 = new javax.swing.JLabel();
        Deducere = new javax.swing.JLabel();
        venitImpozabil = new javax.swing.JLabel();
        cam2_5 = new javax.swing.JLabel();
        impozitVenit = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        salariuNet = new javax.swing.JLabel();
        sumeColectate = new javax.swing.JLabel();
        SalariuBrutLei = new javax.swing.JTextField();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 204, 51));
        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("      Calculator Salariu Net 2018");
        jLabel1.setName(""); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 153));
        jLabel2.setText("Salariu brut in lei");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setText("CAS - 25%");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setText("Deducere personala");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel5.setText("CASS - 10%");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel7.setText("Venit Impozabil");

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel9.setText("Contributia asiguratorie pentru munca - 2.25%\t");

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel11.setText("Impozit pe venit - 10%");

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel13.setText("Giustonel Edition Copyright 2018");

        Calculeaza.setText("Calculeaza");
        Calculeaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculeazaActionPerformed(evt);
            }
        });

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        CAS25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        CAS10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        Deducere.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        venitImpozabil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        cam2_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        impozitVenit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel17.setText("Salariu Net");

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel18.setText("Sume colectate de stat");

        salariuNet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        sumeColectate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        SalariuBrutLei.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                SalariuBrutLeiInputMethodTextChanged(evt);
            }
        });
        SalariuBrutLei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalariuBrutLeiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Deducere, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cam2_5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(impozitVenit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(venitImpozabil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CAS10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9)
                    .addComponent(jLabel2)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CAS25, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(salariuNet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sumeColectate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SalariuBrutLei)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(139, 139, 139)
                            .addComponent(jLabel13))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Calculeaza)
                            .addGap(61, 61, 61)
                            .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(200, 200, 200)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(SalariuBrutLei, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CAS25, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addComponent(CAS10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Deducere, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(venitImpozabil, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11))
                    .addComponent(impozitVenit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cam2_5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(salariuNet, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sumeColectate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Calculeaza)
                    .addComponent(Exit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void SalariuBrutLeiInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_SalariuBrutLeiInputMethodTextChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_SalariuBrutLeiInputMethodTextChanged

    private void SalariuBrutLeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalariuBrutLeiActionPerformed
        // TODO add your handling code here:
        Double x;
        x = Double.parseDouble(SalariuBrutLei.getText());
    }//GEN-LAST:event_SalariuBrutLeiActionPerformed
 
    private void CalculeazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculeazaActionPerformed
  
         double x=Double.parseDouble(SalariuBrutLei.getText());
        try {
            x=Double.parseDouble(SalariuBrutLei.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"ne");
        }
       
       
    double CAS;
    double CASS;
    double Deducere = 0;
    double VenitImp;
    double Impvenit;
    double CAMM;
    double salariuNet;
    double sumeColectate;
    CAS=0.25*x;
    CASS=0.1*x;
    if (x<=3600)
    {
    if (x>=1 && x<=1950)
    {  Deducere=510;
       this.Deducere.setText(Double.toString(Deducere));
    }
    else  if (x>1950 && x<=2000)
    {  Deducere=495;
       this.Deducere.setText(Double.toString(Deducere));
    }
     else  if (x>2000 && x<=2050)
    {  Deducere=480;
       this.Deducere.setText(Double.toString(Deducere));
    }
     else  if (x>2050 && x<=2100)
    {  Deducere=465;
       this.Deducere.setText(Double.toString(Deducere));
    }
     else  if (x>2100 && x<=2150)
    {  Deducere=450;
       this.Deducere.setText(Double.toString(Deducere));
    }
     else  if (x>2150 && x<=2200)
    {  Deducere=435;
       this.Deducere.setText(Double.toString(Deducere));
    }
     else  if (x>2200 && x<=2250)
    {  Deducere=420;
       this.Deducere.setText(Double.toString(Deducere));
    }
     else  if (x>2250 && x<=2300)
    {  Deducere=405;
       this.Deducere.setText(Double.toString(Deducere));
    }
     else  if (x>2300 && x<=2350)
    {  Deducere=390;
       this.Deducere.setText(Double.toString(Deducere));
    }
     else  if (x>2350 && x<=2400)
    {  Deducere=375;
       this.Deducere.setText(Double.toString(Deducere));
    }
     else  if (x>2400 && x<=2450)
    {  Deducere=360;
       this.Deducere.setText(Double.toString(Deducere));
    }
     else  if (x>2450 && x<=2500)
    {  Deducere=345;
       this.Deducere.setText(Double.toString(Deducere));
    }
     else  if (x>2500 && x<=2550)
    {  Deducere=330;
       this.Deducere.setText(Double.toString(Deducere));//corect
    }
     else  if (x>2550 && x<=2600)
    {  Deducere=315;
       this.Deducere.setText(Double.toString(Deducere));
    }
     else  if (x>2600 && x<=2650)
    {  Deducere=300;
       this.Deducere.setText(Double.toString(Deducere));
    }
     else  if (x>2650 && x<=2700)
    {  Deducere=285;
       this.Deducere.setText(Double.toString(Deducere));
    }
     else  if (x>2700 && x<=2750)
    {  Deducere=270;
       this.Deducere.setText(Double.toString(Deducere));
    }
     else  if (x>2750 && x<=2800)
    {  Deducere=255;
       this.Deducere.setText(Double.toString(Deducere));
    }
     else  if (x>2800 && x<=2850)
    {  Deducere=240;
       this.Deducere.setText(Double.toString(Deducere));
    }
     else  if (x>2850 && x<=2900)
    {  Deducere=225;
       this.Deducere.setText(Double.toString(Deducere));
    }
     else  if (x>2900 && x<=2950)
    {  Deducere=210;
       this.Deducere.setText(Double.toString(Deducere));//corect
    }
     else  if (x>2950 && x<=3000)
    {  Deducere=195;
       this.Deducere.setText(Double.toString(Deducere));
    }
     else  if (x>3000 && x<=3050)
    {  Deducere=180;
       this.Deducere.setText(Double.toString(Deducere));
    }
     else  if (x>3050 && x<=3100)
    {  Deducere=165;
       this.Deducere.setText(Double.toString(Deducere));
    }
     else  if (x>3100 && x<=3150)
    {  Deducere=150;
       this.Deducere.setText(Double.toString(Deducere));
    }
     else  if (x>3150 && x<=3200)
    {  Deducere=135;
       this.Deducere.setText(Double.toString(Deducere));
    }
     else  if (x>3200 && x<=3250)
    {  Deducere=120;
       this.Deducere.setText(Double.toString(Deducere));//corect
    }
     else  if (x>3250 && x<=3300)
    {  Deducere=105;
       this.Deducere.setText(Double.toString(Deducere));
    }
     else  if (x>3300 && x<=3350)
    {  Deducere=90;
       this.Deducere.setText(Double.toString(Deducere));
    }
     else  if (x>3350 && x<=3400)
    {  Deducere=75;
       this.Deducere.setText(Double.toString(Deducere));
    }
     else  if (x>3400 && x<=3450)
    {  Deducere=60;
       this.Deducere.setText(Double.toString(Deducere));
    }
     else  if (x>3450 && x<=3500)
    {  Deducere=45;
       this.Deducere.setText(Double.toString(Deducere));
    }
     else  if (x>3500 && x<=3550)
    {  Deducere=30;
       this.Deducere.setText(Double.toString(Deducere));
    }
     else  if (x>3550 && x<=3600)
    {  Deducere=15;
       this.Deducere.setText(Double.toString(Deducere));
    }
   
    }
    else if(x>3600)
        Deducere=0;
        this.Deducere.setText(Double.toString(Deducere));
    //Calcul CAS

    CAS=0.25*x;
    CAS25.setText(Double.toString(CAS));
    //Calcul CASS
    CASS=0.1*x;
    CAS10.setText(Double.toString(CASS));
    //Venit Impozabil
    
    VenitImp=x-CAS-CASS-Deducere;
    venitImpozabil.setText(Double.toString(VenitImp));
    
    Impvenit=0.1*VenitImp;
    impozitVenit.setText(Double.toString(Impvenit));
    
    CAMM=0.0225*x;
    cam2_5.setText(Double.toString(CAMM));
    salariuNet=x-CAS-CASS-Impvenit;
    this.salariuNet.setText(Double.toString(salariuNet));
    sumeColectate=CAS+CASS+CAMM+Impvenit;
    this.sumeColectate.setText(Double.toString(sumeColectate));
                
    
    
            
        
        
    
        
    
    
    
    
    
        
    
    

        
        
        
        
    }//GEN-LAST:event_CalculeazaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorSalariuNet2018.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorSalariuNet2018.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorSalariuNet2018.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorSalariuNet2018.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorSalariuNet2018().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CAS10;
    private javax.swing.JLabel CAS25;
    private javax.swing.JButton Calculeaza;
    private javax.swing.JLabel Deducere;
    private javax.swing.JButton Exit;
    public javax.swing.JTextField SalariuBrutLei;
    private javax.swing.JLabel cam2_5;
    private javax.swing.JLabel impozitVenit;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel salariuNet;
    private javax.swing.JLabel sumeColectate;
    private javax.swing.JLabel venitImpozabil;
    // End of variables declaration//GEN-END:variables

    private String getText() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
